### ISSUE TITLE
Bug: на карточке компонента контекст игнорирует source

### ISSUE THREAD

**Issue by biakaveron** [RabotaRu/DocHub#103]
```
source: >           # Отбираем все компоненты у которых кастомное поле "environment" = "production"
      (               
          $ ~> | $ | {
              "components": $merge(components.$spread().(
                  $.*.environment = 'production' ? $ : {}
              )) 
          } |
      )
```

Вот такой source использую в контексте. На самой странице контекста все ок, фильтрует. Если провалиться в карточку компонента, то выбранный контекст рендерит все связанные компоненты, без учета фильтра. 

Dochub последней версии (2.3.1). В плагине поведение такое же.

**Comment by rpiontik** [comment]
Исправлено.
