### ISSUE TITLE
Bug: неверная ссылка, отправляемая на сервер plantuml, для отрисовки схемы из docs.yaml при работе с GitLab

### ISSUE THREAD

**Issue by vvprokhorov** [RabotaRu/DocHub#104]
При попытке отрисовать схему, описанную в docs.yaml, при работе с GitLab возникает неправильное формирование ссылки для отрисовки, в результате чего сервер возвращает ошибку 404.
DocHub генерит ссылку ниже:
https://gitlab.goodsteam.tech/api/v4/projects/4680/repository/files/Operations%2Fcomponents%2FOMS%2FDocs%2FSchemas%2Fcluster.puml/raw?ref=main?id=OMS_schema_cluster
а должно быть вот так:
https://gitlab.goodsteam.tech/api/v4/projects/4680/repository/files/Operations%2Fcomponents%2FOMS%2FDocs%2FSchemas%2Fcluster.puml/raw?ref=main&id=OMS_schema_cluster

**Comment by rpiontik** [comment]
Исправлено https://github.com/RabotaRu/DocHub/releases/tag/v2.3.2
