### ISSUE TITLE
Ошибка рендеринга Plantuml при наличии "-" в id  компонента

### ISSUE THREAD

**Issue by Nightmarevav** [RabotaRu/DocHub#119]
Ввиду ограничений рендеринга Plantuml , предложение добавить на уровень Core проверок, валидацию id -ников на предмет соответствия этим ограничениям и чтобы в плагине подсвечивались не валидные id.

**Comment by rpiontik** [comment]
Проверки добавлены в схему и соглашения по идентификаторам SEAF. Вскоре будут опубликованы.
