### ISSUE TITLE
После смены контекста - он не помещается на экране расширения(не хватает скролла)

### ISSUE THREAD

**Issue by gituser3000** [RabotaRu/DocHub#128]
В случае, если контекст SELF маленький, а тот, на который переключаем - большой.
Версия расширения в ide jetbrains 1.21.4-beta
Пример:
[Репа dochub examples. ](https://github.com/rpiontik/DocHubExamples/tree/main/src/business_entity_management)
- src/business_entity_management/dochub.yaml
- компонент crm
- переключаем из self в гк болото
- 
![image](https://user-images.githubusercontent.com/15774676/206767345-4c64a928-fd5f-4ff3-975a-b23344b07009.png)

workaround - скопировать plantuml

**Comment by rpiontik** [comment]
Данное поведение признано штатным. 
Скролинг и масштабирование можно осуществлять удерживая кнопку "SHIFT" и используя ролик мышки и курсор.
