### ISSUE TITLE
Ошибка рендера plantuml в плагине

### ISSUE THREAD

**Issue by biakaveron** [RabotaRu/DocHub#130]
```
@startuml
!include <logos/kafka>
!include <logos/postgresql>
!include <logos/python>
!include <logos/aws-s3>
!include <logos/aws-sqs>

node erp
rectangle "APP" {
queue "<$kafka>\nqueue" as kafka
database "<$postgresql>\ndatabase" as pgsql
rectangle "<$python>\nfastapi" as python
}

cloud AWS {
    rectangle "<$aws-s3>\ns3"
    rectangle "<$aws-sqs>\nsqs"
}

erp -> kafka : создан документ
kafka -> python : подтянуть документы
python --> pgsql : сохранить в бд

@enduml
```

Рендер в плагине PlantUML IDEA - норм. В онлайн-редакторе plantuml.com и самого докхаба рендерится. Только плагин выдает ошибку 

![image](https://user-images.githubusercontent.com/95280/207094006-25d49aff-6a8c-4abc-b77a-4b530c6d8ffe.png)

И дело точно не в include, без логотипов тоже выдает ошибку. Похоже, что некоторые типы диаграмм на плагине недоступны.

**Comment by vlad-markin** [comment]
Попробова на свежей версии плагина. Всё норм. Прпедлагаю закрывать.

![image](https://github.com/RabotaRu/DocHub/assets/99147412/c5d27fa1-cebe-4a31-a861-43009a927fe6)
