### ISSUE TITLE
Некорректный рендеринг PlatnUML при использовании "правильного" сервера

### ISSUE THREAD

**Issue by kukuRUSik** [RabotaRu/DocHub#136]
Описание объекта
`@startuml
title Пример сетевого устройства
rectangle "sbercloud" {
    rectangle "ЦОД 1" {
        node "Пример сетевого устройства"
        component "sbbroker.servers.examples"
        "Пример сетевого устройства" <--> "sbbroker.servers.examples"
        component "profkon.servers.examples_2"
        "Пример сетевого устройства" <--> "profkon.servers.examples_2"
    }
}
@enduml
`

Наблюдаемый результат
![image](https://user-images.githubusercontent.com/10906784/209327715-08040686-85b7-4ae5-99d4-c6dcaeb17015.png)

Ожидаемый результат
![image](https://user-images.githubusercontent.com/10906784/209327788-4db06225-0b28-4ca6-8df0-151af17ed991.png)

**Comment by vlad-markin** [comment]
Сейчас рекомендованная сборка:

https://github.com/vlad-markin/plantuml-server собирать из ветки dochub-v2  Dockerfile.jetty
образ на docker hub
seaf/plantuml-server:jetty

Картинка формируется корректно:

https://seaf.su/seafplantuml/svg/fKvD2e905DvxYeTxXLf7Lmb_dX7gZCnC4OIWTeNMjMiTXL0Gdk7DZPeX5q8BgLRVuts_QgKo13hfYkxqf5PNe6i33RLqfOvkr87UwretHj7Hmrw6k80ZC581MngtAqCKKSRNiGixS00659tfI0UOz0m0ux5zVrtelkqHpmlEa2dR6WgUel0bYWqAwUCso8iCPI_zgMJcUVFnwC6AGl0avUn3kPZ-FsCqkxHGmWi0

Предлагаю закрыть.
