### ISSUE TITLE
"Сохранить на диск" плагин Idea под Windows некорректная кодировка и сохраняет не в UTF8BOM

### ISSUE THREAD

**Issue by Nightmarevav** [RabotaRu/DocHub#143]
При попытке экспорта диаграммы контекста через "Сохранить на диск"  плагин Idea под Windows формирует "битый" файл - некорректная кодировка(внутри файла Win1251) и сохраняет не в UTF8 with BOM.
![image](https://user-images.githubusercontent.com/19774254/211360866-97b47a56-fb50-4bc6-b20f-3fabbba721b5.png)

Пример выгрузки:
![test](https://user-images.githubusercontent.com/19774254/211358541-8dcb8e81-d92f-44ac-9934-6f35e1f0c7c5.svg)
Чтобы исправить файл, нужно выполнить ряд операций, например в VSCode:
1. Открыть как Win1251,сохранить в Win1251
2. Открыть и сохранить в UTF8BOM

**Comment by rpiontik** [comment]
Исправлено в ядре 2.6.2
