### ISSUE TITLE
Не обновляются данные виджета в карточке ОА

### ISSUE THREAD

**Issue by cdsmika** [RabotaRu/DocHub#148]
Не обновляются данные виджета в карточке ОА при переходе по иерархии компонентов из ОА с пустыми значениями.
Шаги к воспроизведению:
1. Перейти в карточку с технологиями.
![image](https://user-images.githubusercontent.com/105941129/212837549-c2524c69-d7dd-4e68-8a6a-d469b2c8cc12.png)
2. В иерархии перейти в карточку без технологий - перечень пустой.
![image](https://user-images.githubusercontent.com/105941129/212837658-e604335e-a3d1-4580-aa64-7f0edd533233.png)
3. Вернуться в иерархии в исходную карточку ОА - перечень все еще пустой.
![image](https://user-images.githubusercontent.com/105941129/212837820-7c690215-c49a-4810-a8fb-2e93f496ddac.png)
4. После обновления страницы перечень, заполнен как ожидалось.

**Comment by rpiontik** [comment]
Исправлено в 2.6.1
