### ISSUE TITLE
Низкая скорость работы JSONata функции wcard

### ISSUE THREAD

**Issue by cu3blukekc** [RabotaRu/DocHub#186]
Для сравнения:
![image](https://user-images.githubusercontent.com/575826/218683951-25d94408-2300-4941-b03b-52cea8e839ff.png)

![image](https://user-images.githubusercontent.com/575826/218684444-019bf56e-cc1f-49e1-bc5a-ddb0a9a3307c.png)

Количество
`$USED` - 251 шт
`$.components`  - 553 шт

Пример запроса (валидатор "Компоненты вне контекста" - `dochub.metamodel.contexts.outof`):

```
(
  $MANIFEST := $;
  $USED := $distinct(contexts.*.components);
  [components.$spread().(
      $ID := $keys()[0];
      {
          "id" : $ID,
          "mask" : $USED[$wcard($ID, $)]
      }
  )[$not($exists(mask))].{
    "uid": "$dh-mm-ofb-" & id,
    "correction": "Добавьте компонент в контекст",
    "description": "Предполагается, что компонент не включенный в контекст не учтен.",
    "location": "/architect/components/" & id
  }]
)
```

**Comment by rpiontik** [comment]
Оптимизировал. Надеюсь поможет.
