### ISSUE TITLE
Не работает рендеринг puml из контекста

### ISSUE THREAD

**Issue by cdsmika** [RabotaRu/DocHub#196]
Плагин и UI DocHub (v 2.6.3) пишут ошибку при попытке отрисовать любой puml.
![photo_2023-02-21_11-20-36](https://user-images.githubusercontent.com/105941129/220287929-90966d37-7360-48d5-a460-f4b5fc56bc50.jpg)
![photo_2023-02-21_11-20-32](https://user-images.githubusercontent.com/105941129/220287937-7b10cb2e-d9fc-4df0-b348-6c9c2fa1a386.jpg)

Код из манифеста:
`  drx.L4:
    title: Диаграмма последовательности
    icon: settings_ethernet
    location: Sbermarket/Internal IT/Directum RX/Диаграмма
    components:
      - sbmt.internal_it.drx
    uml: С4/L4.puml`
    
![photo_2023-02-21_11-22-09](https://user-images.githubusercontent.com/105941129/220288234-666c6cfe-c6f9-436b-8039-e15675c31134.jpg)

**Comment by rpiontik** [comment]
Исправление в master.

Сама проблема не изспралена, т.к. лежит в области описания PlantUML. Исправлен вывод ошибки, для того, чтобы пользователь мог разобраться с ее причиной.

**Comment by cdsmika** [comment]
@startuml
!theme vibrant

actor KA

KA-> xde : Документы

xde -> archiveXDE : binary file (xml)
xde -> archiveXDE : binary file (pdf)
xde -> archiveXDE : sgn
drx -> xde : Запрос сообщений (Формализованные)
xde -> drx :  Ответ на запрос (ID документов)
drx -> archiveXDE : Запрос на вложения (поиск по ID)
archiveXDE -> drx : binary file (xml)
archiveXDE -> drx : binary file (pdf)
archiveXDE -> drx : sgn

drx -> xde : Запрос сообщений (Неформализованные)
xde -> drx :  Ответ на запрос (ID документов)
drx -> archiveXDE : Запрос на вложения (поиск по ID)
archiveXDE -> drx : binary file (pdf)
archiveXDE -> drx : sgn

drx -> drx : согласование
drx -> drx : Подписание

drx -> xde : Запрос сообщений (Абон. Ящики)
xde -> drx :  Ответ на запрос
xde -> drx : Абоненсткие ящики
drx -> drx : Контрагенты

drx -> xde : Запрос сообщений (Статусы)
xde -> drx :  Ответ на запрос (Статусы)
drx -> drx : Обработка (Статусы)

drx -> archiveXDE : xml
drx -> archiveXDE : pdf
drx -> archiveXDE : sgn
drx -> archiveXDE : id Документа
drx -> archiveXDE : Обновление файла

drx -> xde : Обновление (ID, Статусы)

archiveXDE -> xde : binary file (xml)
archiveXDE -> xde : binary file (pdf)
archiveXDE -> xde : sgn
KA <- xde : Документы

@enduml

**Comment by cdsmika** [comment]
А что тут может быть неправильно?)
Я пробовал любой puml
