### ISSUE TITLE
Преждевременное сообщение "Нет данных" при отрисовке таблиц

### ISSUE THREAD

**Issue by AndrewBiz** [RabotaRu/DocHub#204]
Сделали таблицу для отображения систем компании. Запрос, готовящий данные для таблицы, получися довольно тяжелым - от 2 до 5 секунд выполняется. Все это время у пользователя перед глазами висит пустая таблица с надписью "нет данных". Многие успевают огорчиться или испугаться. Дабы не нарушать душевный покой пользователя предлагаю до до момента получения данных для таблицы, чтобы движок либо отрисовывал что-то типа индикатора прогресса, либо хотя-бы убрать надпись нет данных и заменить ее на "идет чтение данных"

![image](https://user-images.githubusercontent.com/809234/222646228-15d0d973-3d22-4a12-a01b-eb5ec76bb003.png)

**Comment by rpiontik** [comment]
Исправлено в 3.0.0 версии
