### ISSUE TITLE
Символ "проваливания вглубь" "≫≫" отображается через пробел 

### ISSUE THREAD

**Issue by formatq** [RabotaRu/DocHub#21]
Символ _проваливания вглубь_ "≫≫" отображается как будто через пробел.
![image](https://user-images.githubusercontent.com/3082584/150919105-9c8d30f9-26dc-4a87-b185-0db8a2863d34.png)

ветка archops-conception-v2

**Comment by rpiontik** [comment]
Багуля под контролем. 
Символ проваливания сейчас очень временный. Позже будет проведен рефакторинг дизайна. Как заведется дизайнер :)
Ожидать быстрого решения не стоит.
Но тикет закрывать не буду. Пусть будет напоминанием.

**Comment by rpiontik** [comment]
Вопрос передан в дизайн.
