### ISSUE TITLE
Feature Request: Добавить новую сущность References

### ISSUE THREAD

**Issue by formatq** [RabotaRu/DocHub#22]
Отталкиваясь от интерфейса информации о компоненте, где отображаются блоки Сводка, Контекст, Документ, Иерархия, добавить еще один блок - References. 

В этом блоке будут перечислены ссылки на внешнюю документацию с краткий описанием ссылки (например. формате md).
References нужны в момент, когда переносить ранее созданную документацию внутрь DocHub, например, из конфлюенса, трудозатратно, поэтому на первом этапе описания было бы неплохо видеть ссылки на первоисточники.

**Comment by rpiontik** [comment]
Данная функция может быть реализована в версии 2.2.1-beta путем создания шаблонов рендеринга документов. Вы можете создать собственные, любые, расширения метамодели и рендерить их по собственным требованиям.
