### ISSUE TITLE
Feature Request: Плагин DocHub для Intellij Idea

### ISSUE THREAD

**Issue by formatq** [RabotaRu/DocHub#23]
Очень не хватает подсказок при добавлении аспектов и links. 

плагин будет сканировать текущие файлы и компоненты и будет помогать при добавлении новых элементов/связей при описании архитектуры.

Такая возможность станет киллер фичей для этого проекта :)

**Comment by rpiontik** [comment]
Однозначно будет создаваться в ближайшее время.
Запрос на эту фичу высокий.

**Comment by rpiontik** [comment]
Плагин создан. Будет опубликован в течении двух рабочих дней. Пока можно попробовать его установив из файла:
[IDEAPlugin-1.4-beta.zip](https://github.com/RabotaRu/DocHub/files/7969400/IDEAPlugin-1.4-beta.zip)
