### ISSUE TITLE
Возможность задавать стили для entity

### ISSUE THREAD

**Issue by formatq** [RabotaRu/DocHub#24]
Можно ли как то задать entity стиль, например, изменить цвет?

попробовал добавить uml в описание ентити:
```
title: пример
entity: rectangle
aspects:
  - bla.blabla
uml:
  $before: >
    skinparam classFontColor red
```
но это не сработало

**Comment by rpiontik** [comment]
Можно. Вы идете в верном направлении. То, что стиль не применился, скорее всего, связано с его некорретным описанием. 

Чтобы проверить, в браузере откройте консоль (F12 в Chrome). При генерации диаграммы в консоль выводится сгенерированный PlantUML. Можно посмотреть как он собирается. И протестировать на сервер PlantUML. Например тут - http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuNBCoKnELT2rKt3AJx9IS2mjoKZDAybCJYp9pCzJ24ejB4qjBk42oYde0jM05MDHLLoGdrUSoeLkM5u-K5sHGY9sGo6ARNHr8QeJSQc66kwGcfS2SZ00

**Comment by formatq** [comment]
Спасибо, понял. 

Но только при указании в контексте все стили ко всем инстансам элемента применяется. А для конкретного rectangle можно добавить стиль? 

Например, хочется обозначить элемент как внешний сервис в виде прямоугольника другого цвета.
попробовал внутри контекста такое, но не сработало (ошибка в dochub, в plantUML этот блок появляется, но игнорится):
```
...
    uml:
      $before: >
        skinparam component<<some.component>> {
          backgroundColor DarkKhaki
        }
...
```
и так тот же результат :
```
...
    uml:
      $before: >
        skinparam component {
          backgroundColor<<some.component>> DarkKhaki
        }
...
```

**Comment by rpiontik** [comment]
Тут можно пойти глубже и переопределить нотацию. Это более правильный путь, чтобы стандартизировать ваши объекты.

Делается это в файле src/assets/plantuml_dsl.txt

Сейчас это "прибито" гвоздями. Но вскоре будет возможность нотацию подключать так же как манифесты.

**Comment by formatq** [comment]
так, это уже сложновато получается. Но в целом спасибо за ответы.
