### ISSUE TITLE
Некоректная работа настройки VUE_APP_DOCHUB_APPEND_DOCHUB_DOCS

### ISSUE THREAD

**Issue by vvprokhorov** [RabotaRu/DocHub#247]
При выставлении в файле .env настройки VUE_APP_DOCHUB_APPEND_DOCHUB_DOCS = "n" вместе с документацией по DocHub пропадают и все остальные разделы меню "Документы". Ниже пруфы:
VUE_APP_DOCHUB_APPEND_DOCHUB_DOCS = "y"
![изображение](https://user-images.githubusercontent.com/111460949/226989548-c002c0d6-288c-4ed7-8062-564da1127b60.png)
VUE_APP_DOCHUB_APPEND_DOCHUB_DOCS = "n"
![изображение](https://user-images.githubusercontent.com/111460949/226989097-4dcbbd15-1da3-4e60-874e-6a4a80422084.png)

**Comment by vlad-markin** [comment]
Сейчас должно работать. По крайней мере активно пользуемся разделом "документы". Предлагаю закрыть, или дать подробности воспроизведения: описание или ссылку на репозиторий с примером.
