### ISSUE TITLE
Feature Request: Тогл extra-links для контекста SELF

### ISSUE THREAD

**Issue by formatq** [RabotaRu/DocHub#25]
Очень не хватает возможности просмотра входящих связей компонента от других компонентов

Например, допустим у нас есть 10 разных сервисов и все делают запросы в сервис А. 
У каждого сервиса мы прописываем, что он ссылается на этот сервис А. 
Просматривая SELF-контекст каждого сервиса мы видим связь с сервисом А. 
Но зайдя на страницу SELF-контекста сервиса А мы ничего не увидим, потому что внутри компонента сервиса А нет никаких описаний связей. 

Дублировать эти связи очень накладно в плане поддержки. Поэтому нужна возможность отображения SELF-контекст включая extra-links (например, в виде кнопки включения/выключения или дополнительной вкладки self-with-extra-links), как это делается при описании контекстов.

**Comment by rpiontik** [comment]
Этот кейс рассматривался. Он ведет к неуправляемости отображением. Были случаи большого числа линков на один компонент. Поэтому стратегия выбрана такая, что компонент показывается с тем, от чего сам зависит.

В целом, представления можно доработать. Немного позже дам пример как это можно сделать самому. Без кодинга.

**Comment by formatq** [comment]
Спасибо за ответ. Буду ждать примера.
А с какими ограничения столкнулись по отображению? PlantUml не справлялся? И вы имеете ввиду сложности только с первым уровнем связи (одно "колено")?

Мне кажется это прям киллер-фича была бы. Лично мне достаточно было 1 уровня, и тогда смотря на self-схему можно по всему проекту перемещаться. А если бы у компонента было очень много входящих ссылок то насильно отображать только те которые у него прописаны с припиской, мол, компонент имеет много связей, отображение ограничено.

**Comment by rpiontik** [comment]
Получались нечитабельными. Например Gateway превращался в паука. И непонятно было от чего ОН зависит. 

На выходных пример подготовлю

**Comment by formatq** [comment]
> Получались нечитабельными. Например Gateway превращался в паука. И непонятно было от чего ОН зависит.
Понятно. А можно это сделать как некий тогл в интерфейсе?

**Comment by rpiontik** [comment]
Задаче решается через кастомизацию поведения контекста.
