### ISSUE TITLE
id перезатирается при передаче в документ

### ISSUE THREAD

**Issue by mumg** [RabotaRu/DocHub#273]
Вызываем документ с параметром
http://localhost:8081/docs/arch.business.capabilities.details.group?id=XXX
Ожидаемое поведение: params.id в jsonata запросе = XXX
Полученное поведение: params.id = arch.business.capabilities.details.group, тоесть идентификатору документа

**Comment by mumg** [comment]
полученное поведение: любые параметры не пробрасываются в документ

**Comment by rpiontik** [comment]
В данном случае параметр перезаписывается параметром передающимся в Entity документа для его представления. Необходимо использовать идентификаторы параметров имеющие уникальность. Например:

1. stakeholderid
2. customerid
и т.п.

Также желательно выбрать для себя префекс для всех параметров. Например "mts-". Тогда параметры приобретут вид:

1. mts-stakeholderid
2. mts-customerid
и т.п.

В сущности базовой метамодели внесены соответствующие исправления и примеры.

Исправлено в v3.0.2-fix1
