### ISSUE TITLE
не работает трейсинг JSONATA

### ISSUE THREAD

**Issue by mumg** [RabotaRu/DocHub#274]
не вызывается метод  

isTraceJSONata(): boolean {
    return (this.dochub.VUE_APP_DOCHUB_JSONATA_ANALYZER || 'N').toUpperCase() === 'Y';
  },

соответсвенно не работает трейсинг в консоль

**Comment by rpiontik** [comment]
Исправлено в v3.0.2-fix1

**Comment by rpiontik** [comment]
В данном случае параметр перезаписывается параметром передающимся в Entity документа для его представления. Необходимо использовать идентификаторы параметров имеющие уникальность. Например:

1. stakeholderid
2. customerid
и т.п.

Также желательно выбрать для себя префекс для всех параметров. Например "mts-". Тогда параметры приобретут вид:

1. mts-stakeholderid
2. mts-customerid
и т.п.

В сущности базовой метамодели внесены соответствующие исправления и примеры.

Исправлено в v3.0.2-fix1
