### ISSUE TITLE
Cors error

### ISSUE THREAD

**Issue by Andrey-cisco** [RabotaRu/DocHub#279]
После обновления с версии 2.6.5 на 3.0.1 или 3.0.2 возникает ошибка 
Acess to XMLHttpRequest at 'gitlab:2492:master@dochub.yaml' from origin 'xxx' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.

Где xxx - домен url самого докерхаба

В старой версии в процессе загрузки страницы докхаб ходил в гит по ссылке 
https://yyy/api/v4/projects/2492/repository/files/dochub.yaml/raw?ref=master

В новой версии пытается по 
gitlab:2492:master@dochub.yaml

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/53005887/233570822-2a286442-2694-46b0-9b31-cc45939f28d4.png">

<img width="1715" alt="image" src="https://user-images.githubusercontent.com/53005887/233571052-336a8a1d-a270-40fc-8316-3a90d6fae3c4.png">

**Comment by rpiontik** [comment]
Исправлено. В master
