### ISSUE TITLE
В версии 3.0.2 диаграмма SELF контекста отображаются некорректно

### ISSUE THREAD

**Issue by apoddubny** [RabotaRu/DocHub#281]
Используется стандартная метамодель.
На странице компонента  рисуется диаграмма, которая не имеет никакого отношения к SELF контексту. Также пропали из переключателя контекстов пропали все остальные контексты.

**Comment by apoddubny** [comment]
UP
Диаграмма имеет отношение к SELF контексту. Просто на ней отображаются, кроме связей с выбранным компонента, еще и связи **между** остальными компонентами, попавшими на эту схему.

**Comment by rpiontik** [comment]
Исправлено в fix3
