### ISSUE TITLE
Заменить хранилищие in-memory в бекенд режиме на любое statefull (redis, elastic, mysql, postgres, etc)

### ISSUE THREAD

**Issue by apoddubny** [RabotaRu/DocHub#283]
Проблема: текущее решение может работать только в одной реплике. Невозможно гарантировать, что данные в одном из экземпляров полностью совпадут с данными в другом.

Для того, чтобы в бекенд режиме докхаб мог работать в нескольких репликах, необходимо заменить текущее in-memory хранилище на любое statefull решение.

**Comment by rpiontik** [comment]
Реализовано в v3.6.0.
