### ISSUE TITLE
Если нет связей в системе, то система не попадает в контекст

### ISSUE THREAD

**Issue by ValentinKozlov** [RabotaRu/DocHub#287]
Не выводится в контекст система, если в ней нет связей.
Пример контекста: 
https://github.com/ValentinKozlov/DocHubExamples/blob/main/src/repository_structure_example/artefacts/common/pal1_landscape.yaml
Пример системы: 
https://github.com/ValentinKozlov/DocHubExamples/blob/main/src/repository_structure_example/application_arch/systems/sid.yaml

**Comment by rpiontik** [comment]
Не воспроизводится.
