### ISSUE TITLE
Feature Request: Выпадающий список вместо вкладок контекстов

### ISSUE THREAD

**Issue by formatq** [RabotaRu/DocHub#29]
При просмотре аспектов список контекстов, в которых встречается аспект, отображается в табах. 
Если названия контекстов длинные (а они обычно длинные), то промотать на самый последний контекст можно только прощелкав все табы. (пример #28)

Было очень удобней смотреть сразу весь список контекстов, в которых встречается аспект. Например, в выпадающем списке, где навигация до последнего контекста была бы в два клика.

**Comment by rpiontik** [comment]
Реализовано.
