### ISSUE TITLE
При подключении внешней метамодели в VS Code дублируются данные в плагине

### ISSUE THREAD

**Issue by ValentinKozlov** [RabotaRu/DocHub#292]
При подключении внешней метамодели в VS Code дублируются данные в плагине, при этом данные в Web версии не дублируются. 

Что было сделано в web версии:
1. В .env отключил свою метамодель
`# VUE_APP_DOCHUB_METAMODEL = /workspace/metamodels/_root.yaml`
2. Подключил свою метамодель в своём репозитории 
imports: 
  - metamodels/_root.yaml
 
Не смотря на то, что я ожидаю что метамодель задет штатная, заехала полностью моя.

При работе в плагине заезжает адская смесь.

**Comment by rpiontik** [comment]
Исправлен в 3.3.0
