### ISSUE TITLE
Не загружается внешняя метамодель в режиме бэкенда

### ISSUE THREAD

**Issue by ValentinKozlov** [RabotaRu/DocHub#294]
Сценарий:
1. Выношу метамодель в репозиторий, но импорт её внутри репозитория не делаю:
```
imports:
  - custom/_root.yaml
  # - dochub/_root.yaml  
  - datasets/_root.yaml  
  - jsonata/_root.yaml
```
2. Подключаю внешнюю метамодель в .env `VUE_APP_DOCHUB_METAMODEL = /workspace/metamodels/dochub/_root.yaml`
3. Запускаю в режиме фронта `npm run serve` - метамодель загружается
4. Запускаю в режиме бэкенда `npm run backend` - метамодель НЕ загружается

**Comment by rpiontik** [comment]
Исправлено fix6.
