### ISSUE TITLE
Не работает API для сущностей

### ISSUE THREAD

**Issue by ValentinKozlov** [RabotaRu/DocHub#295]
Сценарий:
1. Создаю API в таком виде:
```
      get_business_entities:
          type: upload
          title: Выгрузка бизнес-сущностей в JSON
          # template: templates/temporary.json   
          origin: swamp.dataset.business_entities_in_systems       # Базовый источник данных
          source: >
            (
                $[system_id="swamp.crocodile.crm"]
            )
```
2. Запускаю DocHub  в режиме бэкенд `npm run backend`
3. По правой кнопке мыши выгружаю JSON файл - все выгружается
4. Пробую выгрузить по URL `http://localhost:3030/entities/business_entities/presentations/get_business_entities` - падает по ошибке "{"message":"Not found required field [template]. Location [/entities/business_entities/presentations/get_business_entities]"}"
5. Создаю шаблон со следующим кодом {{content}}
6. Подключаю шаблон template: templates/temporary.json
7. Перезапускаю бэкенд
8. Пытаюсь выгрузить файл вручную - файл не формируется
9. Пробую выгрузить по URL `http://localhost:3030/entities/business_entities/presentations/get_business_entities` - падает по ошибке " {"message":"Unexpected token { in JSON at position 1","error":{}} "
10. Страдаю

**Comment by rpiontik** [comment]
Исправлено fix6
