### ISSUE TITLE
В отображении swagger-файлов не учитывается информация в верхнем блоке

### ISSUE THREAD

**Issue by formatq** [RabotaRu/DocHub#30]
В swagger-файлах не отображается информация о названии и описании того API, которое отображается ниже.
![image](https://user-images.githubusercontent.com/3082584/151512195-499b5142-93c5-493b-b223-c5a87f72bfda.png)

а должно быть примерно так:
![image](https://user-images.githubusercontent.com/3082584/151512449-45dc5aa5-b304-487e-b51b-4023152959a0.png)

**Comment by rpiontik** [comment]
Исправлено.
