### ISSUE TITLE
Ошибка рендеринга схем при большой вложенности объектов

### ISSUE THREAD

**Issue by apoddubny** [RabotaRu/DocHub#302]
Вложенность отображается неправильно, не хватает закрывающих скобок.

**Comment by DenisV-Fokin** [comment]
Тоже наткнулся на такую ошибку. Вот простейший пример, когда начинает воспроизводиться (ниже также приведен код plantUML): 

components:
  product:
    title: Product
    entity: collections
  product.container1:
    title: container1
    entity: collections
  product.container1.comp1_1:
    title: comp1_1
    entity: collections
  product.container1.comp1_1.comp1_1_1:
    title: comp1_1_1
    entity: component
  product.container1.comp1_2:
    title: comp1_2
    entity: collections
  product.container1.comp1_2.comp1_2_1:
    title: comp1_2_1
    entity: component
  product.container2:
    title: container2
    entity: collections
  product.container2.comp2_1:
    title: comp2_1
    entity: collections
  product.container2.comp2_1.comp2_1_1:
    title: comp2_1_1
    entity: component


contexts:
  main:
    title: Диаграмма с ошибкой
    location: Диаграммы/С ошибкой
    components:
      - product.**

Генерируется такой PlantUml:

  $Header("Диаграмма с ошибкой", "", "" , "")
  $Region(product,"[[/architect/components/product Product]]", ) {
  $Region(product.container1,"[[/architect/components/product.container1 container1]]", ) {
  $Region(product.container1.comp1_1,"[[/architect/components/product.container1.comp1_1 comp1_1]]", ) {
  $Entity("component", "[[/architect/components/product.container1.comp1_1.comp1_1_1 comp1_1_1]]", product.container1.comp1_1.comp1_1_1, )
  $EntityEnd("component")
}
  $Region(product.container1.comp1_2,"[[/architect/components/product.container1.comp1_2 comp1_2]]", ) {
  $Entity("component", "[[/architect/components/product.container1.comp1_2.comp1_2_1 comp1_2_1]]", product.container1.comp1_2.comp1_2_1, )
  $EntityEnd("component")
}
  $Region(product.container2,"[[/architect/components/product.container2 container2]]", ) {
  $Region(product.container2.comp2_1,"[[/architect/components/product.container2.comp2_1 comp2_1]]", ) {
  $Entity("component", "[[/architect/components/product.container2.comp2_1.comp2_1_1 comp2_1_1]]", product.container2.comp2_1.comp2_1_1, )
  $EntityEnd("component")
}
