### ISSUE TITLE
Feature Request: Возможность выделить стрелку связи компонета

### ISSUE THREAD

**Issue by formatq** [RabotaRu/DocHub#31]
Иногда стрелка связи в схеме может быть длинной и хотелось бы ее как то подсветить, что бы при навигации по схеме можно было  проследить куда эта стрелка ведет

пример графа зависимостей maven в Idea

https://user-images.githubusercontent.com/3082584/152117430-a72467cb-fd49-49b8-bbfc-dbae96a6f0fa.mov

**Comment by rpiontik** [comment]
Фича добавлена. 
К сожалению не работает для движка ELK.
