### ISSUE TITLE
Не корректная ссылка на docs в карточке components

### ISSUE THREAD

**Issue by Jolidze** [RabotaRu/DocHub#310]
Из карточки сущности components генерируется не рабочая ссылка на docs, при клике ошибка (см картинку ниже).

Саму ссылку могу поправить (вместо "/docs/" & $id  прописать "/entities/docs/blank?dh-doc-id=" & id), но нет доступа чтоб карточку компонента править.

![LinkFromComponentsToDocs](https://github.com/RabotaRu/DocHub/assets/111694934/ad8a6381-d871-4b6f-9098-c8a347d5ce8e)

**Comment by rpiontik** [comment]
Исправлено в мастере.
