### ISSUE TITLE
Feature request: на диаграммах SmartAnts не отображается заголовок

### ISSUE THREAD

**Issue by Jolidze** [RabotaRu/DocHub#317]
На диаграммах PlantUML заголовок (title) отображается вверху посередине, на диаграммах SmartAnts не отображается нигде, прошу добавить.

![FR title on SmartAnts](https://github.com/RabotaRu/DocHub/assets/111694934/650bbcb7-c1c7-4c9a-93f2-8272d9076ba3)

**Comment by rpiontik** [comment]
Реализовано в v3.1.0
