### ISSUE TITLE
Feature request: на диагаммах SmartAnts нет возможности управлять цветом связей (links)

### ISSUE THREAD

**Issue by Jolidze** [RabotaRu/DocHub#318]
Прошу реализовать возможность назначать цвет для связей (links) на диаграммах SmartAnts.

Пример кейса: пусть связи имеют атрибут "частота использования",  нужна возможность наглядно выделить на диаграмме цветом самые часто используемые связи.

![FR color links](https://github.com/RabotaRu/DocHub/assets/111694934/1083f936-52e6-47c6-b304-589f126e4d70)

**Comment by rpiontik** [comment]
Реализовано.
