### ISSUE TITLE
Feature request: на диаграммах Smart Ants нет возможности ограничить максимальную толщину жгута

### ISSUE THREAD

**Issue by Jolidze** [RabotaRu/DocHub#330]
При сворачивании интеграционных потоков в жгуты, толщина жгута пропорциональна количеству входящих в него потоков; нет возможности ограничить максимальную толщину жгута.
При разрастании количества связей, диаграммы выглядят не эстетично:

![FR 1 - ограничение толщины жгута](https://github.com/RabotaRu/DocHub/assets/111694934/4808d9e8-d91b-48e0-866e-7bd7a6c20e07)

**Comment by rpiontik** [comment]
Реализовано в v3.1.0
