### ISSUE TITLE
Feature request: на диаграммах Smart Ants нет возможности сделать кликабельным title потока

### ISSUE THREAD

**Issue by Jolidze** [RabotaRu/DocHub#331]
Я описываю потоки данных в кастомной сущности threads, каждый поток имеет свою карточку.
Требуется сделать  title потока кликабельным, чтобы при нажатии на ссылку попадать в его карточку, аналогично components.

![FR 2 - кликабельное имя потока](https://github.com/RabotaRu/DocHub/assets/111694934/b207e249-53e4-44c5-8dd5-c4b165271f69)

**Comment by rpiontik** [comment]
Реализовано в v3.1.0

**Comment by vlad-markin** [comment]
реализовано. Давайте закрывать
