### ISSUE TITLE
Feature request: на диаграммах Smart Ants нет возможности скрывать названия компонент (нод)

### ISSUE THREAD

**Issue by Jolidze** [RabotaRu/DocHub#332]
Иногда названия компонент диаграммы (нод) избыточны, необходимо управлять их отображением, выбирать отображать/скрывать их.

![FR 3 - отображать имена компонент (нод)](https://github.com/RabotaRu/DocHub/assets/111694934/7305db3b-0d52-4090-996d-8d2623ff0b4e)

**Comment by vlad-markin** [comment]
реализовано. Давайте закрывать.
