### ISSUE TITLE
Feature request: возможность перейти от компонента до схемы (контекста) где он упоминается, даже если схема не собрана автоматом

### ISSUE THREAD

**Issue by jumangee** [RabotaRu/DocHub#338]
Есть заранее подготовленная схема и понимание, что на ней есть те или иные компоненты, описанные в dochub. Хочется иметь возможность обратного перехода от "компонента к контексту", даже если контекст не собирался автоматически. Это приблизит функционал ручных схем к функционалу автоматических, в то время как сейчас ручных контексты это просто бесполезные рисунки (нет никакой связи с компонентами)

Можно трактовать, что "если в контексте есть список components И схема собрана руками через uml", то отображать этот контекст в списке тех компонентов, которые перечислены, при этом автоматическую сборку схемы не делать.

**Comment by rpiontik** [comment]
Реализовано в v3.1.0
