### ISSUE TITLE
Авторизация только через корень 

### ISSUE THREAD

**Issue by ultimaster1** [RabotaRu/DocHub#34]
Если давать ссылку на созданный раздел не авторизированному раннее пользователю, то схема не отобразиться, на веб-морде не появиться никаких предупреждений, при этом фронт будет ловить ошибку 401
![image](https://user-images.githubusercontent.com/29702142/153182191-e44afca1-6912-47c4-8f0a-84cad4b1a89c.png)
Авторизоваться можно только через корень - https://dochub2.rabota.space/ , только при переходе по этой ссылке пользователя перекинет на страницу авторизации

**Comment by rpiontik** [comment]
Испралено.
