### ISSUE TITLE
Bug: Схемы отображаются некорректно на сайте dochub

### ISSUE THREAD

**Issue by Akkarine** [RabotaRu/DocHub#35]
![image](https://user-images.githubusercontent.com/13115270/153747579-277a2f5e-26bd-4c70-a0e1-310a7645ff86.png)

Chrome 98.0.4758.82, включен "ночной режим".

**Comment by rpiontik** [comment]
Спасибо за информацию! 

Рендериг схем на dochub.info происходит на публичном сервере PlantUML. Видимо на публичном сервере PlantUML выкатилось неудачное обновление. Сейчас я наблюдаю, что на некоторых компьютерах фон стал серым, а на некоторых отображается черным. 

Если ситуация не исправится сама до завтра, буду разбираться в деталях.

**Comment by rpiontik** [comment]
Бага "самоутраняется" силами PlantUML команды. На всех доступных мне устройствах схемы вновь стали читабельными.
