### ISSUE TITLE
Плагин Idea 3.4.0 перестал работать zoom

### ISSUE THREAD

**Issue by Nightmarevav** [RabotaRu/DocHub#350]
Плагин Idea 3.4.0,  перестал работать zoom 
информация об окружении: 
IntelliJ IDEA 2023.1.5 (Community Edition)
Build #IC-231.9392.1, built on July 25, 2023
Runtime version: 17.0.7+10-b829.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 8
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.andrey4623.rainbowcsv (2.0.2)
    Key Promoter X (2023.2.0)
    String Manipulation (9.10.0)
    org.dochub.idea.arch (3.4.0)
    PlantUML integration (6.3.0-IJ2022.2)
    izhangzhihao.rainbow.brackets (2023.3.2)

Kotlin: 231-1.8.21-IJ9392.1

**Comment by rpiontik** [comment]
И на маке проверить

**Comment by Nightmarevav** [comment]
![image](https://github.com/RabotaRu/DocHub/assets/19774254/539ef311-a739-4280-bc36-287032d24fc5)
@rpiontik  Зум заработал в 3.5.0, но теперь при зуме внизу обрезает.
org.dochub.idea.arch (3.5.0)

**Comment by rpiontik** [comment]
Исправлено в v3.6.0
