### ISSUE TITLE
Возможность кастомизации карточки системы

### ISSUE THREAD

**Issue by cu3blukekc** [RabotaRu/DocHub#354]
Хотелось бы иметь возможность штатными средствами (без дорабток ядра) заменить страницу компонента на свой плагин, в котором уже организовать свой интерфейс.

Например
вот это заменить на свой плагин
![image](https://github.com/RabotaRu/DocHub/assets/575826/52780b97-08f7-4044-9131-3299b6fe7777)

**Comment by rpiontik** [comment]
Решено в v3.3.0
