### ISSUE TITLE
Vscode плагин не работает в WSL и Devcontainer

### ISSUE THREAD

**Issue by ypolosov** [RabotaRu/DocHub#359]
<details>
<summary>VS Code System Information</summary>

# VS Code System Information

## OS Information

| key | value |
|---|---|
| arch | x64 |
| platform | linux |
| type | Linux |
| release | 5.15.90.1-microsoft-standard-WSL2 |
| EOL | "\\n" |
| endianness | LE |

## Process Information

| key | value |
|---|---|
| arch | x64 |
| env | {} |

### versions

| key | value |
|---|---|
| node | 16.17.1 |
| v8 | 9.4.146.26-node.22 |
| uv | 1.43.0 |
| zlib | 1.2.11 |
| brotli | 1.0.9 |
| ares | 1.18.1 |
| modules | 93 |
| nghttp2 | 1.47.0 |
| napi | 8 |
| llhttp | 6.0.9 |
| openssl | 1.1.1q+quic |
| cldr | 41.0 |
| icu | 71.1 |
| tz | 2022a |
| unicode | 14.0 |
| ngtcp2 | 0.1.0-DEV |
| nghttp3 | 0.1.0-DEV |

## VS Code Information

| key | value |
|---|---|
| version | 1.81.1 |

</details>

### Описание проблемы

1. Windows 10 (работает)
![image](https://github.com/RabotaRu/DocHub/assets/5928235/67cfdb55-b79b-440d-abda-88a907345d39)
2. WSL (не работает)
![image](https://github.com/RabotaRu/DocHub/assets/5928235/cce8c4f7-9c18-4b3f-ae64-344e2900f935)
3. Devcontaier (не работает)
![image](https://github.com/RabotaRu/DocHub/assets/5928235/27411520-cf0a-4d2f-802d-b12249a8494c)

**Comment by rpiontik** [comment]
Исправлено в 0.0.25
