### ISSUE TITLE
Ошибка рендеринга PlantUML (414 Request-URI Too Large)

### ISSUE THREAD

**Issue by crygazm** [RabotaRu/DocHub#411]
Подняли докхаб и получаем такого рода ошибки (не на всех страницах но на некоторых)

![image](https://github.com/RabotaRu/DocHub/assets/148547299/15aeb5ed-2e7c-4ace-b37e-e8ae857c99e9)

<details>

<summary>Длина запроса генерится более 10к символов</summary>

</details>

**Comment by vlad-markin** [comment]
Посмотрите https://github.com/vlad-markin/plantuml-server ветку dochub-v2 из неё можно собрать Dockerfile.jetty, там увеличена длинна запроса до 65k. Готовый образ можно взять докерхаба: docker run -d -p 8080:8080 seaf/plantuml-server:jetty
Если докер за проксёй, то нужно ещё увеличить размер на ней. Например, для nginx:
large_client_header_buffers 4 65k;
