### ISSUE TITLE
Функционал для внедрения изображений в описание 

### ISSUE THREAD

**Issue by ultimaster1** [RabotaRu/DocHub#43]
В данный момент нет возможности вставлять изображения средствами DocHub, при использовании .md файлов средствами html (![image info](example.png)) - 
![image](https://user-images.githubusercontent.com/29702142/160646651-ffd7a08d-54ea-4fee-99bd-5cae11b40c20.png)

**Comment by rpiontik** [comment]
![image](https://user-images.githubusercontent.com/20013842/162586450-749a7420-7455-45f7-a981-92eb4552da1e.png)
Готово.
