### ISSUE TITLE
[Bug] SmartAnts title and footer overlapping

### ISSUE THREAD

**Issue by villanella** [RabotaRu/DocHub#465]
Related to #421 
При масштабе диаграммы более 80%  происходит обрезка заголовка и нижней части диаграммы.
Наличие или отсутствие кастомных параметров distance, trackWidth ситуацию не меняет. Прокрутки диаграммы нет. Workaround - только уменьшать масштаб, но будет трудночитаемо.

Верх диаграммы (обрезан заголовок):
![pic-selected-231130-1150-28](https://github.com/RabotaRu/DocHub/assets/4890566/8135820c-ed7f-42f9-a7ad-37d38021c062)

Низ диаграммы (обрезана нижняя граница блоков и нижняя строка подписи "Yandex Tracker"): 
![pic-selected-231130-1214-10](https://github.com/RabotaRu/DocHub/assets/4890566/176fd73d-f267-4298-8f81-1b58e20e5f34)

**Comment by rpiontik** [comment]
Исправлено в [v3.12.0](https://github.com/RabotaRu/DocHub/releases/tag/v3.12.0)
