### ISSUE TITLE
При авторизации в gitlab, плагин работает не корректно

### ISSUE THREAD

**Issue by ContinentalGuy** [RabotaRu/DocHub#489]
При авторизации в gitlab, плагин работает не корректно.
В редиректе пропадает параметр, по которому производится идентификация.
В консоли выдается ошибка:
`Это не плагин...`

**Comment by rpiontik** [comment]
Исправлено в [v3.12.0](https://github.com/RabotaRu/DocHub/releases/tag/v3.12.0)
