### ISSUE TITLE
Reload в браузерах на chromium

### ISSUE THREAD

**Issue by ContinentalGuy** [RabotaRu/DocHub#497]
Заметили что на хромиуме через раз работает авторизация в gitlab после перезагрузки страницы, из-за чего документы то отображаются, то появляется ошибка:
```
Неизвестный тип документа [unknown]
Path: /entities/docs/presentations/blank
Params: {"dh-doc-id": "..."}
Profile:
{"$base": "/entities/docs/presentations/blank"}
```

При первой загрузке страницы видна ошибка. 
Поэтому нужно сразу два релоада сделать, чтобы посмотреть на документ.

На том же ПК решили проверить, есть ли такие проблемы в firefox.
Оказалось что с firefox таких проблем нет. После каждой перезагрузки авторизация проходила успешно и документ загружался.

Было бы здорово это исправить, потому что большая часть коллег не пользуется firefox, а заставлять их переходить с любимого браузера на firefox - не хочется.

**Comment by rpiontik** [comment]
Исправлено в [v3.12.0](https://github.com/RabotaRu/DocHub/releases/tag/v3.12.0)
