### ISSUE TITLE
[Bug] Ошибки подключения внешней метамодели из Gitlab к серверу

### ISSUE THREAD

**Issue by villanella** [RabotaRu/DocHub#507]
При подключении метамоделей из отдельного репозитория на Докхаб-сервере возникают ошибки c ненайденными зависимостями Dochub и seaf-метамоделей. Модели при этом не работают.

Использую сервер Dochub (npm run serve или npm run backend), запущенный из папки Dochub 3.9. Стандартная метамодель Докхаба лежит локально в public/metamodel/dochub - то есть в локации умолчанию.

Настройки .env указывают на репозиторий с облегченными seaf-метамоделями из Гитлаба с доступом по токену:

```
VUE_APP_DOCHUB_METAMODEL = gitlab:1233:master@dochub.yaml (также пробовала подключать сюда dochub.yaml из одной из seaf-метамоделей или общий yaml из папки _metamodel_)
VUE_APP_DOCHUB_ROOT_MANIFEST=gitlab:1233:master@dochub.yaml
```

Cтруктура репозитория с метамоделями:
```
_metamodel_/seaf-core
_metamodel_/seaf-dzo-core
_metamodel_/packages.yaml  # здесь подключаются обе метамодели seaf
dochub.yaml    # здесь ссылка на packages.yaml
другие файлы
```

Сервер выдает ошибку c ненайденными метамоделями и неразрешенной зависимостью dochub 3.9.0:
![pic-selected-240305-1400-21](https://github.com/RabotaRu/DocHub/assets/4890566/fec514d9-f2bb-4b36-bffa-3f46ef735742)

При этом плагин Идеи в репозитории метамодели нормально работает, поскольку метамодель в нем локально расположена и подключена корректно.

Обходной путь: добавить ММ в виде ссылки в public/workspace так, чтоб она была локальной для сервера. 

Остальные Gitlab-импорты из манифестов, если применить для метамодели обходной путь, работают на сервере корректно, токен валиден.

**Comment by rpiontik** [comment]
Исправлено в [v3.12.0](https://github.com/RabotaRu/DocHub/releases/tag/v3.12.0)
