### ISSUE TITLE
Поддержка git submodule

### ISSUE THREAD

**Issue by no1seman** [RabotaRu/DocHub#518]
Проблема:
У нас несколько десятков различных репозиториев dochub, при этом все они содержат общие части: кастомную метамодель, общие компоненты, и т.д.

Что бы все это сращивать в каждом репозитрии используем механизм импорта: gitlab:<project_id>:<branch_id>@root.yaml

Он более или менее работает, но это жутко неудобно, потому что:
- репозиторий находится в VPN, а не всегда есть возможность подключиться, при этом необходимо локально что-то править и потом смотреть во вьювере плагина. Без VPN это невозможно.
- разные репозитории в один момент времени могут смотреть в разные версии общих компонентов и например неудачный push в ветку  импортируемого репозитория ломает сразу всё, а держать 100500 веток для версий - это неудобно: плохо контролируемо и много лишних телодвижений.
- в некотором будущем необходимо будет использовать не один сервер, а несколько, т.к. часть репозиториев будет передаваться в другие подразделения.

Что предлагается:
Решением всех вышеперечисленных проблем является использование git submodule. если все необходимые внешние зависимости будут подтягиваться в том числе сервером из сабмодулей, тогда можно будет и локально с ними работать без VPN и пушить в репозиторий, а сервер будет их скачивать, при этом появляется возможность управлять общими зависимостями на уровне коммита.

**Comment by SychevIgor** [comment]
Где-то тут должно появится слово- Федеративное управление архитектурой.

**Comment by rpiontik** [comment]
Мне кажется, этот функционал реализуется самим гитом. Он не требует от DocHub каких-то доработок.
