### ISSUE TITLE
Отображение связей в контекстах

### ISSUE THREAD

**Issue by apoddubny** [RabotaRu/DocHub#59]
В контекстах должна быть возможность описывать(или указывать) именно те стрелки, которые я хочу видеть. 
Для конкретного контекста интересуют именно конкретные связи внутри систем, другие будут лишь засорять схему.

(при этом неплохо оставить текущую возможность просто указать системы)

**Comment by rpiontik** [comment]
Данное поведение реализуется через кастомизацию контекстов.
