### ISSUE TITLE
Поддержка dotted lines в links (<..>)

### ISSUE THREAD

**Issue by AndrewBiz** [RabotaRu/DocHub#63]
Предлагается поддержать возможность задавать пунктирные стрелки на схемах. Стандартный plantuml это поддерживает, цитата: Links between elements are made using combinations of dotted line (..), straight line (--), and arrows (-->) symbol

Пример:
components:
  example_system:
    title: Система
    entity: component
    links:
      - id: system2
        direction: <..>

**Comment by rpiontik** [comment]
Данная возможность уже есть. Все типы связей, которые поддерживает PlantUML доступны. 
![Снимок экрана от 2022-07-29 09-40-09](https://user-images.githubusercontent.com/20013842/181698719-34a6d7dc-943d-4223-ae9a-6fc7887fe5e5.png)
рендерится так:
![Снимок экрана от 2022-07-29 09-39-03](https://user-images.githubusercontent.com/20013842/181698663-c544df22-1983-4359-b40a-64ec5969dbe0.png)

**Comment by AndrewBiz** [comment]
упс. действительно работает. проверил в плагине 1.18Beta. До этого смотрел на предыдущей версии, ну не работало!
