### ISSUE TITLE
Feature Request: возможность определить набор полей через forms для любого набора компонент

### ISSUE THREAD

**Issue by scscsc123** [RabotaRu/DocHub#67]
Текущая реализация: набор доп. полей задается в разрезе каждого entity единственным набором (https://arch.sblogistica.ru/docs/dochub.forms)

Так как за архитектурным компонентом могут стоять различные по сути сущности (системы, подсистемы, микросервисы, бизнес-домены и проч.) с потенциально совершенно отличным друг от друга атрибутным составом, то _хотелось бы расширить возможность гибкого определения набора доп.полей_ в разрезе _произвольного_ набора компонент (в дискуссии упоминалась реализация через фильтр).

**Comment by rpiontik** [comment]
Решено в релизе v2.1.0
