### ISSUE TITLE
Bug: в сводку компонента не выводится набор полей из forms, если поля задавать через массив

### ISSUE THREAD

**Issue by scscsc123** [RabotaRu/DocHub#69]
Для описания архитектуры СБЛ необходимо задать один набор дополнительных полей для компонентов с entity = component (читай - для системы или ее слагающих), другой набор дополнительных полей для компонентов с entity = actor (для бизнес-владельцев систем). Для этого требуется описание полей в forms через массив (см. приложенный рисунок).
Баг состоит в том, что использование синтаксиса массива проглатывается докхабом (то есть ошибка не выдается), но при этом новые поля на компонентах не появляются, хотя должны.

p.s.: если задавать общий набор доп.полей forms единой кучей, то есть один набор для нескольких entity, то проблем нет.

![image](https://user-images.githubusercontent.com/109514993/182122488-48c95ec5-9dd0-41c4-82cd-c5a0a2c24b6e.png)

**Comment by rpiontik** [comment]
Решено в релизе v2.1.0
