### ISSUE TITLE
Возможность сохранения json всего арх. репозитория

### ISSUE THREAD

**Issue by AndrewBiz** [RabotaRu/DocHub#77]
Сделали возможность в контексте (на картинке) по правой кнопке "скопировать json" - это оч. удобно для опытов в https://try.jsonata.org/.
Но проблема в том, что таким образом выгружается не весь репо, а отфильтрованная его часть (фильтр - это контекст). А мне нужен именно весь "глобальный" json - хочется на нем отрабатывать выборки с помощью jsonata - чтобы потом получившиеся сниппеты использовать внутри контекста для преобразования источника (см. доку https://dochub.info/docs/dochub.contexts - в самом конце)

**Comment by rpiontik** [comment]
Решено в релизе 2.2.2-beta
