### ISSUE TITLE
Нет явного описания формата URI для работы с gitlab

### ISSUE THREAD

**Issue by cgi** [RabotaRu/DocHub#96]
К сожалению не смог найти явно в документации описания формата URI для работы с репозиториями gitlab.

По результату анализа кода получилось так: 
gitlab:{projectID}:{branch}@{path}

Было бы зорово осветить это в документации ( секция импорт?) и/или в README

P.S. 
Так же только в одной из статей нашел правила поиска корневого манифеста.

**Comment by vlad-markin** [comment]
Есть в описании example.env
#       Структура ссылки:
#       gitlab      - протокол GitLab
#       34          - идентификатор репозитория
#       main        - бранч
#       root.yaml   - путь к файлу

но, наверное, да, лучше добавить в ридми

**Comment by rpiontik** [comment]
Добавлено в документацию.
