### ISSUE TITLE
entity: class

### ISSUE THREAD

**Issue by altershaman** [RabotaRu/DocHub#97]
Невозможно использовать entity: class
![79AE5D28-633B-480F-9B6A-8F5FD3B73FC3](https://user-images.githubusercontent.com/57250198/192488523-6b5ec879-830c-45aa-a892-f83d820b60cd.jpeg)

**Comment by kukuRUSik** [comment]
Расширю проблему - невозможно использовать нотация за пределами deployment-diagram.
К примеру, для детального описания конкретного сервиса было бы не плохо использовать нотацию class-diagram (https://plantuml.com/ru/class-diagram).
