### ISSUE TITLE
Доработка формы (глобальное влияние данных формы)

### ISSUE THREAD

**Issue by ruDmitry** [RabotaRu/DocHub#98]
Доработка формы.

На текущий момент создание формы и добавления в нее компонент оказывает глобальное влияние на ДокХаб.
Необходимо ограничить глобальное влияние и дать возможность указывать на какие компоненты влияет форма

**Comment by rpiontik** [comment]
Этот запрос решился добавлением функционала виджетов. Подробно о них узнать можно здесь - https://github.com/rpiontik/DocHubExamples/tree/main/src/widgets
