### ISSUE TITLE
Bug: Проблемы рендеринга PlantUML при `-` в имени компонента/контекста

### ISSUE THREAD

**Issue by kukuRUSik** [RabotaRu/DocHub#99]
При использовании `-` в имени **компонента** получаем **ошибку рендеринга** PlantUML.
При использовании `-` в имени **контекста** получаем **зависание рендеринга** PlantUML.

**Comment by rpiontik** [comment]
Символ "-" нельзя использовать в идентификаторе. 
Если проблема на последней релизе сохраняется и не связана с идентификатором, откройте пожалуйста тикет вновь с примером.
